# Generated by Django 3.2.5 on 2021-07-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_cities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cities',
            new_name='City',
        ),
    ]
