# Generated by Django 3.2.5 on 2021-07-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Город'),
        ),
    ]
